version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '13306:3306' # ホストからゲストへポートフォワード
    volumes:
      - mysql-data:/var/lib/mysql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/speadwear2 # ソースコード変更したらDocker側も即反映されるように
volumes:
  mysql-data:
    driver: local
