export const initialState = {
  items: {
    itemId: '',
    season: '',
    tpo: '',
    superItem: '',
    rating: '',
    content: '',
    size: '',
    gender: '',
    price: '',
    description: '',
    images: [],
  },
  coordinates: {
    coordinateId: '',
    season: '',
    tpo: '',
    rating: '',
    content: '',
    gender: '',
    price: '',
    description: '',
    images: [],
  },
  users: {
    isSignedIn: false,
    orders: [],
    admin: false,
    id: '',
    name: '',
  },
  apis: {
    loading: '',
    error: '',
  },
}
