import { formatDiagnosticsWithColorAndContext, isForStatement } from 'typescript'

export const initialState = {
  items: {
    id: '',
    uid: '',
    coordinateId: '',
    superItem: '',
    season: '',
    tpo: '',
    color: '',
    content: '',
    gender: '',
    size: '',
    price: '',
    description: '',
    image: [],
    rating: '',
  },
  coordinates: {
    id: '',
    uid: '',
    itemId: '',
    commentId: '',
    likeCoordinateId: '',
    season: '',
    tpo: '',
    gender: '',
    size: '',
    price: '',
    image: [],
    rating: '',
    siShoes: '',
    siBotttoms: '',
    siTops: '',
    siOuter: '',
    description: '',
  },
  users: {
    id: '',
    isSignedIn: false,
    name: '',
    email: '',
    image: '',
    gender: '',
    coordinateId: '',
    itemId: '',
    commentId: '',
    admin: false,
    passwordDigest: '',
    resetDigest: '',
    activationDigest: '',
    activated: '',
  },
  apis: {
    loading: '',
    error: '',
  },
}
